
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules  # Exclure `node_modules` de la synchronisation des volumes pour éviter les conflits entre hôte et conteneur
    stdin_open: true
    tty: true
